[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"

  [entryPoints.http]
    address = ":80"


  [entryPoints.https]
    address = ":443"

[acme]
email = "nyancetch@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[providers.docker]
domain = "localhost"
watch = true
network = "web"